In [61]:
import numpy as np
import pandas as pd
data = pd.read_csv(r"C:\Users\DELL\Desktop\ML using python\files\Heart.csv")
data.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [62]:
# Group by column name
# df = data.groupby('Thal').nunique()
# df

In [63]:
# Transform ChestPain & Thal string data to numeric data
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["ChestPain"]=le.fit_transform(data["ChestPain"])
data["Thal"]=le.fit_transform(data["Thal"].astype(str))
data["AHD"]=le.fit_transform(data["AHD"].astype(str))
# data

In [64]:
# Removing null values
null_val = ['Age','Sex','ChestPain','RestBP','Chol','Fbs','RestECG','MaxHR','Oldpeak','Slope','Ca','Thal','AHD']
for col in null_val:
    data[col] = data[col].replace(0, np.nan)
    mean = int(data[col].mean(skipna=True))
    data[col] = data[col].replace(np.nan, mean)

#data

In [65]:
x = data[['Age','Sex','ChestPain','RestBP','Chol','Fbs','RestECG','MaxHR','Oldpeak','Slope','Ca','Thal']].values
y = data['AHD'].values
#y = data.iloc[:, 0].values 

In [66]:
#X = data.iloc[:, [0,8,3,6]].values

In [53]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[:, 0] = labelencoder.fit_transform(X[:, 0])

In [67]:
# X = X.reshape(len(x), 1)
print(X)

[[  0. 150.   3.   1.]
 [  1. 108.   1.   1.]
 [  2. 129.   1.   1.]
 ...
 [300. 115.   1.   1.]
 [301. 174.   2.   1.]
 [302. 173.   1.   1.]]


In [68]:
# divide data into training and testing dataset
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(X, y, train_size = 0.80, random_state=0)

In [69]:
# prepare model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [70]:
# train the model
model.fit(xTrain, yTrain)

LinearRegression()

In [71]:
# prediction
yPred = model.predict(xTest)
#yPred

In [72]:
from sklearn.metrics import r2_score
r2 = r2_score(yTest, yPred)
r2

1.0

In [73]:
# cross validation
accu = []
for i in range(1, 101):
  xTrain, xTest, yTrain, yTest = train_test_split(X, y, train_size=0.80, random_state=i)
  model = LinearRegression()
  model.fit(xTrain, yTrain)
  yPred = model.predict(xTest)
  r2 = r2_score(yTest, yPred)
  accu.append(r2)

accu_array = np.array(accu)
print(accu_array)
accu_array.max()

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


1.0