In [264]:
import pandas as pd
import numpy as np

In [265]:
ds = pd.read_csv('play_data.csv')
print(ds)

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No


In [266]:
ds.head()

day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [267]:
ds.tail()

day   outlook  temp humidity    wind play
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [268]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
ds['outlook'] = le.fit_transform(ds['outlook'])
ds['temp'] = le.fit_transform(ds['temp'])
ds['humidity'] = le.fit_transform(ds['humidity'])
ds['wind'] = le.fit_transform(ds['wind'])
ds['play'] = le.fit_transform(ds['play'])

In [269]:
print(ds)

    day  outlook  temp  humidity  wind  play
0    D1        2     1         0     1     0
1    D2        2     1         0     0     0
2    D3        0     1         0     1     1
3    D4        1     2         0     1     1
4    D5        1     0         1     1     1
5    D6        1     0         1     0     0
6    D7        0     0         1     0     1
7    D8        2     2         0     1     0
8    D9        2     0         1     1     1
9   D10        1     2         1     1     1
10  D11        2     2         1     0     1
11  D12        0     2         0     0     1
12  D13        0     1         1     1     1
13  D14        1     2         0     0     0


In [270]:
x = ds[['outlook','temp','humidity','wind']].values
y = ds['play'].values

In [271]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.3)

In [272]:
y_test

array([1, 1, 0, 1, 1])

In [273]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [274]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [275]:
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1, 1, 1])

In [276]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[0, 1],
       [0, 4]])

In [277]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred) * 100
acc

80.0

In [278]:
y_new = model.predict([[2,0,0,0]])
if y_new == 1:
    print("Play Game")
else:
    print("Do Not Play Game")

Play Game
