In [24]:
import pandas as pd


In [25]:
data = pd.read_csv('Salary_Data.csv')
data.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 608.0 bytes


In [27]:
x= data[['YearsExperience']].values
y= data['Salary'].values

type(x)


numpy.ndarray

In [28]:
print(x,'\n\n', y)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]] 

 [ 39343  46205  37731  43525  39891  56642  60150  54445  64445  57189
  63218  55794  56957  57081  61111  67938  66029  83088  81363  93940
  91738  98273 101302 113812 109431 105582 116969 112635 122391 121872]


In [29]:
x.shape
y.shape

(30,)

In [30]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [31]:
# shape of feature should be(no. of samples, no. of features)
#x=x.reshape(len(x),1)
#print(x)

In [32]:
# divide data into training and testing samples
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, train_size = 0.80, random_state=1)


In [33]:
xtrain

array([[ 9.5],
       [ 2. ],
       [ 8.7],
       [ 7.9],
       [ 8.2],
       [ 2.2],
       [ 1.5],
       [ 9. ],
       [ 3. ],
       [ 5.9],
       [ 4.1],
       [ 3.2],
       [ 9.6],
       [ 1.3],
       [ 5.1],
       [ 1.1],
       [ 4.9],
       [10.5],
       [10.3],
       [ 3.7],
       [ 3.2],
       [ 4. ],
       [ 4. ],
       [ 2.9]])

In [34]:
xtest

array([[5.3],
       [7.1],
       [3.9],
       [6. ],
       [4.5],
       [6.8]])

In [35]:
ytrain

array([116969,  43525, 109431, 101302, 113812,  39891,  37731, 105582,
        60150,  81363,  57081,  54445, 112635,  46205,  66029,  39343,
        67938, 121872, 122391,  57189,  64445,  56957,  55794,  56642])

In [36]:
ytest

array([83088, 98273, 63218, 93940, 61111, 91738])

In [37]:
#prepare model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [38]:
#train model
model.fit(xtrain, ytrain)

LinearRegression()

In [39]:
#prediction
ypred = model.predict(xtest)
ypred

array([75074.50510972, 91873.8056381 , 62008.38247653, 81607.56642631,
       67608.14931932, 89073.92221671])

In [40]:
ytest

array([83088, 98273, 63218, 93940, 61111, 91738])

In [41]:
from sklearn.metrics import r2_score
r2 = r2_score(ytest, ypred)
r2

0.7616681465472094

In [42]:
#cross validation
accu = []
for i in range(1, 101):
  xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size=0.80, random_state=i)
  model = LinearRegression()
  model.fit(xtrain, ytrain)
  ypred = model.predict(xtest)
  r2 = r2_score(ytest, ypred)
  accu.append(r2)
accu

[0.7616681465472094,
 0.8886956733784562,
 0.9695039421049821,
 0.9504404484884268,
 0.9439628569611375,
 0.9368146227107088,
 0.8143022783109007,
 0.9631182154839476,
 0.9388416537799072,
 0.9816423482070253,
 0.940882728477622,
 0.9429269163491424,
 0.9394460269118793,
 0.9606215790278543,
 0.8697012433817218,
 0.7949890249259295,
 0.9384744808306155,
 0.8864330645841889,
 0.9415531751862448,
 0.9441299149555877,
 0.9398582853702571,
 0.8870702615446784,
 0.9184170849214232,
 0.9520702017424296,
 0.9531732818427658,
 0.9835849730044816,
 0.9636425773684422,
 0.9217841352107623,
 0.9467172742609804,
 0.9944092048209745,
 0.8967649524853983,
 0.8985995727228404,
 0.9350785573211586,
 0.9244141448042442,
 0.8839476512584652,
 0.955021106900739,
 0.9778242092591887,
 0.972479448737762,
 0.9928344802911049,
 0.7775083459037235,
 0.9802519469633169,
 0.9024461774180497,
 0.8688045158887867,
 0.934951117043928,
 0.9250487875802144,
 0.9789129767378081,
 0.98399193890564,
 0.980277279178695,

In [43]:
import numpy as np
acc_array = np.array(accu)
acc_array

array([0.76166815, 0.88869567, 0.96950394, 0.95044045, 0.94396286,
       0.93681462, 0.81430228, 0.96311822, 0.93884165, 0.98164235,
       0.94088273, 0.94292692, 0.93944603, 0.96062158, 0.86970124,
       0.79498902, 0.93847448, 0.88643306, 0.94155318, 0.94412991,
       0.93985829, 0.88707026, 0.91841708, 0.9520702 , 0.95317328,
       0.98358497, 0.96364258, 0.92178414, 0.94671727, 0.9944092 ,
       0.89676495, 0.89859957, 0.93507856, 0.92441414, 0.88394765,
       0.95502111, 0.97782421, 0.97247945, 0.99283448, 0.77750835,
       0.98025195, 0.90244618, 0.86880452, 0.93495112, 0.92504879,
       0.97891298, 0.98399194, 0.98027728, 0.94976703, 0.88246796,
       0.96086247, 0.97436467, 0.95011549, 0.949273  , 0.89241371,
       0.98040674, 0.80963515, 0.48152205, 0.95479901, 0.91399254,
       0.95052229, 0.97195098, 0.9582009 , 0.91400678, 0.81127009,
       0.77822856, 0.95888325, 0.97917871, 0.87118241, 0.94293977,
       0.96947922, 0.95627718, 0.98121431, 0.96185917, 0.96522

In [44]:
acc_array.max()

0.9944092048209745

In [45]:
acc_array.argmax()

29